version: '3.7'
services:
  web:
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - 8000:8000
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - ./dbdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - ./.env